### ISSUE TITLE
AGPL Violation

### ISSUE THREAD

**Issue by ToniOfQ** [FantoX001/Zero-Two#3]
I have checked and reviewed all of the codes with [ShineiIchijo](https://github.com/ShineiIchijo)'s [Chitoge](https://github.com/ShineiIchijo/Chitoge) and I saw that all of the codes are same except the text and some commands are also old commands of Chitoge (which was removed). I also watched your video and you just said "made by me" which is not good. So, I would like you to give proper credits to ShineiIchijo in this repo and re-upload the video by giving proper credits to him. If you don't, I'll definitely report to ShineiIchijo and sue you

**Comment by FantoX001** [comment]
I have talked with ShineiIchijo sir already about it. He just told me not to claim it for myself, so i am modifying the full bot and giving him proper credit. If you don't believe my words you can as ShineiIchijo sir. Or message me on WhatsApp(+918101187835) i will show you proof. 

And the in the YouTube video i accept my guilty. I also told ShineiIchijo sir about it already.

Thank you.
